<h1> H1 TITLE </h1>
<h2> H2 TITLE </h2>

In [63]:
print("Buy the dip ?")

Buy the dip ?


In [68]:
#Exercice 1

import numpy as np
your_np_array = np.array([
    42,                           # integer
    5.14,                         # float
    "Hello",                      # string
    {'key': 'value'},             # dictionary
    [1, 2, 3],                    # list
    (4, 5),                       # tuple
    {1, 2, 3},                    # set
    True                          # boolean
], dtype=object)

##code adding
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [ ]:
#Exercice 2

# Créer un tableau NumPy de dimension 300 rempli de zéros
array_zeros = np.zeros(300)

# Remodeler le tableau en (3, 100)
array_reshaped = array_zeros.reshape(3, 100)

# Afficher le tableau remodelé
print(array_reshaped)


In [67]:
#Exercice3

## 1. Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.
array_1_to_100 = np.arange(1, 101)
print(array_1_to_100)

## 2. Without using a for loop and using the array created in Q1, create an array that contain all odd integers. The expected output is:
all_odd_integers = array_1_to_100[array_1_to_100%2!=0]
print(all_odd_integers)

## 3. Without using a for loop and using the array created in Q1, create an array that contain all even integers reversed. The expected output is:
integers_reversed= array_1_to_100[array_1_to_100 % 2 == 0][::-1]
print(integers_reversed)

## 4. Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0. The expected output is:
array_with_zeros = array_1_to_100.copy()  # Make a copy to avoid modifying the original
array_with_zeros[1::3] = 0  # Set every 3rd element (starting from index 1) to 0
print(array_with_zeros)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58

In [69]:
# Exercise 4

# 1 Régler la valeur de départ du générateur aléatoire
np.random.seed(888)

# 2 Générer un tableau unidimensionnel de taille 100 avec une distribution normale
# Moyenne = 0, Écart type = 1 
normal_array = np.random.normal(loc=0, scale=1, size=100)
print(normal_array)

# 3 Générer un tableau bidimensionnel de taille 8x8 avec des entiers aléatoires de 1 à 10

random_int_array_2d = np.random.randint(1, 11, size=(8, 8))
print(random_int_array_2d)

# 4 Générer un tableau tridimensionnel de taille 4x2x5 avec des entiers aléatoires de 1 à 17

random_int_array_3d = np.random.randint(1, 18, size=(4, 2, 5))
print(random_int_array_3d)

[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6.54547

In [84]:
#Exercise 5
import numpy as np

# 1: Générer un tableau avec des entiers de 1 à 50
array_1_to_50 = np.arange(1, 51)  
print(array_1_to_50)

# 2: Générer un tableau avec des entiers de 51 à 100
array_51_to_100 = np.arange(51, 101)  
print(array_51_to_100)

# 3: Concatenation des deux tableaux
concatenated_array = np.concatenate((array_1_to_50, array_51_to_100))
print(concatenated_array)

# 4: Remodeler le tableau en une matrice de 10 lignes et 10 colonnes
reshaped_array = concatenated_array.reshape(10, 10)

print(reshaped_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  5

In [95]:
#Exercise 6

# 1: Generate a 2-dimensional array of size 9x9 with all elements initialized to 1
array_9x9 = np.ones((9, 9), dtype=np.int8)
print("9x9 Array initialized to 1:")
print(array_9x9)

#2: Modify the array using slicing
array_9x9[1:8, 1:8] = 0  
array_9x9[2:7:2, 1] = 1  
#array_9x9[2:7:2, 2:7] = 1 
#array_9x9[3::2, 0] = 1  
#array_9x9[3::2, 8] = 1 

print("\nModified 9x9 Array:")
print(array_9x9)

#3: Create two arrays
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)

# Use broadcasting to create an output matrix
output_matrix = array_1[:, np.newaxis] + array_2  # Adding with broadcasting
print("\nOutput matrix using broadcasting:")
print(output_matrix)


9x9 Array initialized to 1:
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

Modified 9x9 Array:
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

Output matrix using broadcasting:
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]
