# H1 TITLE

## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


In [3]:
#Exercice 1

import numpy as np
your_np_array = np.array([
    42,                           # integer
    5.14,                         # float
    "Hello",                      # string
    {'key': 'value'},             # dictionary
    [1, 2, 3],                    # list
    (4, 5),                       # tuple
    {1, 2, 3},                    # set
    True                          # boolean
], dtype=object)
print( type(your_np_array))
##code adding
for i in your_np_array:
    print(type(i))

<class 'numpy.ndarray'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [133]:
#Exercice 2
import numpy as np
# Créer un tableau NumPy de dimension 300 rempli de zéros
array_zeros = np.zeros(300)

# Remodeler le tableau en (3, 100)
array_reshaped = array_zeros.reshape(3, 100)

# Afficher le tableau remodelé
print(array_reshaped)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


In [139]:
#Exercice3
import numpy as np
## 1. Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.
integers = np.arange(1, 101)
print(integers)

## 2. Without using a for loop and using the array created in Q1, create an array that contain all odd integers.
all_odd_integers = integers[::2]
print(all_odd_integers)

## 3. Without using a for loop and using the array created in Q1, create an array that contain all even integers reversed. 
integers_reversed= integers[::-2]
print(integers_reversed)

## 4. Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0. The expected output is:
array_with_zeros = integers.copy()  # Make a copy to avoid modifying the original
array_with_zeros[1::3] = 0  # Set every 3rd element (starting from index 1) to 0
print(array_with_zeros)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58

In [3]:
# Exercise 4
import numpy as np
# 1 Régler la valeur de départ du générateur aléatoire
np.random.seed(888)

# 2 Générer un tableau unidimensionnel de taille 100 avec une distribution normale
# Moyenne = 0, Écart type = 1 
normal_array = np.random.randn(100)
print(normal_array)

# 3 Générer un tableau bidimensionnel de taille 8x8 avec des entiers aléatoires de 1 à 10

random_int_array_2d = np.random.randint(1, 11, size=(8, 8))
print(random_int_array_2d)

# 4 Générer un tableau tridimensionnel de taille 4x2x5 avec des entiers aléatoires de 1 à 17

random_int_array_3d = np.random.randint(1, 18, size=(4, 2, 5))
print(random_int_array_3d)

[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6.54547

In [84]:
#Exercise 5
import numpy as np

# 1: Générer un tableau avec des entiers de 1 à 50
array_1_to_50 = np.arange(1, 51)  
print(array_1_to_50)

# 2: Générer un tableau avec des entiers de 51 à 100
array_51_to_100 = np.arange(51, 101)  
print(array_51_to_100)

# 3: Concatenation des deux tableaux
concatenated_array = np.concatenate((array_1_to_50, array_51_to_100))
print(concatenated_array)

# 4: Remodeler le tableau en une matrice de 10 lignes et 10 colonnes
reshaped_array = concatenated_array.reshape(10, 10)

print(reshaped_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  5

In [21]:
# Exercise 6
import numpy as np
# Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.
array_9x9= np.ones((9,9), dtype=np.int8)
print(array_9x9)

# Using slicing, create the following array:
array_9x9[1:8, 1:8]=0
array_9x9[2:7, 2:7]=1
array_9x9[3:6, 3:6]=0
array_9x9[4:5, 4:5]=1
print(array_9x9)

# Using broadcasting create an output matrix based on the following two arrays
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
matrix= array_1[:, np.newaxis]*array_2
print(matrix)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [40]:
# Exercise 7

import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan


third_column = np.where(np.isnan(grades[:, 0 ]), grades[ :, 1], grades[ :, 0] )
grades= np.column_stack((grades, third_column))
print(grades)


[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [9]:
# Exercice 8

# Load the data 
data = np.genfromtxt('winequality-red.txt', delimiter=';', dtype=np.float32)

#verify that the resulting numpy array weighs 76800 bytes.
size_in_bytes = data.nbytes
print("Taille du tableau en octets :", size_in_bytes)

# Display the 2nd, 7th, and 12th rows as a two-dimensional array
selected_rows=data[[1, 6, 11], : ]
filtered_rows = selected_rows[~np.isnan(selected_rows).any(axis=1)]
print(filtered_rows)

#Determine if there is any wine in the dataset with an alcohol percentage greater than 20%
alcohol_column= data[:, 10]
contains_high_alcohol = np.any(alcohol_column > 20)
print("There is any wine in the dataset with an alcohol percentage greater than 20% :", contains_high_alcohol, "\n")

#Calculate the average alcohol percentage across all wines in the dataset. Exclude np.nan values if present.
average_alcohol_percentage = np.nanmean(alcohol_column)
print("Average alcohol percentage across all wines:", average_alcohol_percentage, "\n")

#Compute various statistical measures 
ph_column = data[ :, 8]
min_ph = np.nanmin(ph_column)
max_ph = np.nanmax(ph_column)
mean_ph = np.nanmean(ph_column)
percentile_25 = np.nanpercentile(ph_column, 25)
percentile_50 = np.nanpercentile(ph_column, 50)  # This is the median
percentile_75 = np.nanpercentile(ph_column, 75)

print("Statistical measures for pH values:")
print("Minimum:", min_ph)
print("Maximum:", max_ph)
print("Mean:", mean_ph)
print("25th Percentile:", percentile_25)
print("50th Percentile (Median):", percentile_50)
print("75th Percentile:", percentile_75)


# Average quality score of wines with the 20% least sulphate content.

sulphates_column = data[:, 9]
quality_column = data[:, 11]

# Calculer le 20e percentile de la colonne des sulfates
percentile_20 = np.nanpercentile(sulphates_column, 20)

# Créer un tableau booléen pour les sulfates inférieurs au 20e percentile
low_sulphates_mask = sulphates_column < percentile_20

# Sélectionner les notes de qualité correspondantes
low_sulphates_quality = quality_column[low_sulphates_mask]

# Calculer la moyenne des notes de qualité
average_quality_low_sulphates = np.nanmean(low_sulphates_quality)

# Afficher le résultat
print("\n Average quality score of wines with the 20% least sulphate content:", average_quality_low_sulphates)

#the mean of all variables for wines with the best quality. Also, do the same for wines with the worst quality.

max_quality= np.nanmax(quality_column)

# Trouver la qualité maximale
max_quality = np.nanmax(quality_column)
# Créer un masque booléen pour les vins de la meilleure qualité
best_quality_mask = quality_column == max_quality
# Sous-ensemencer les lignes avec la meilleure qualité
best_quality_wines = data[best_quality_mask]
# Calculer la moyenne pour les vins de meilleure qualité sur l'axe 0
mean_best_quality = np.nanmean(best_quality_wines, axis=0)

min_quality = np.nanmin(quality_column)
# Créer un masque pour les vins de moins bonne qualité
worst_quality_mask = quality_column == min_quality
# Sous-ensemencer les lignes avec une qualité inférieure
worst_quality_wines = data[worst_quality_mask]
# Calculer la moyenne pour les vins de moins bonne qualité sur l'axe 0
mean_worst_quality = np.nanmean(worst_quality_wines, axis=0)

print("\nMean of all variables for wines with the best quality :")
print(mean_best_quality)

print("\nMean of all variables for wines with the worst quality :")
print(mean_worst_quality)


Taille du tableau en octets : 76800
[[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
   0.56    9.4     5.    ]
 [ 7.4     0.66    0.      1.8     0.075  13.     40.      0.9978  3.51
   0.56    9.4     5.    ]
 [ 6.7     0.58    0.08    1.8     0.097  15.     65.      0.9959  3.28
   0.54    9.2     5.    ]]
There is any wine in the dataset with an alcohol percentage greater than 20% : False 

Average alcohol percentage across all wines: 10.422983 

Statistical measures for pH values:
Minimum: 2.74
Maximum: 4.01
Mean: 3.311113
25th Percentile: 3.21
50th Percentile (Median): 3.31
75th Percentile: 3.4

 Average quality score of wines with the 20% least sulphate content: 5.1854305

Mean of all variables for wines with the best quality :
[ 8.566666    0.4233333   0.39111114  2.5777776   0.06844445 13.277778
 33.444443    0.99521226  3.2672222   0.76777774 12.094444    8.        ]

Mean of all variables for wines with the worst quality :
[ 8.359999    0.8845      0.1

In [13]:
#Exercise 9
from itertools import permutations
import numpy as np
import itertools

# Step 1: Load the forecast matrix from file
forecast_matrix = np.genfromtxt('model_forecasts.txt', delimiter=',')

# Generate all permutations of 10 teams
all_permutations = list(permutations(range(10)))

# Initialize variable to store the minimum sum of squared differences and the best pairing
min_sum_squared_diffs = float('inf')
best_pairing = None

def calculate_sum_squared_diffs(perm):
    team_set1 = perm[:5]
    team_set2 = perm[5:]
    squared_diffs = np.square([forecast_matrix[i, j] for i, j in zip(team_set1, team_set2)])
    return np.sum(squared_diffs), (team_set1, team_set2)

# Use map to apply the calculate_sum_squared_diffs function to all permutations
results = map(calculate_sum_squared_diffs, all_permutations)

# Use min to find the best pairing
min_sum_squared_diffs, best_pairing = min(results)

result = [list(pair) for pair in zip(best_pairing[0],best_pairing[1])]
result_np = np.array(result)

# Extract the first and second elements from each sublist
first_elements = result_np[:, 0]
second_elements = result_np[:, 1]

# Construct the wanted_result
wanted_result = np.vstack([first_elements, second_elements])    
wanted_result


array([[0, 1, 2, 3, 5],
       [8, 7, 9, 4, 6]])